### ISSUE TITLE
Scroll position on page reload - Latest version (3.5.4)

### ISSUE THREAD

**Issue by eugeniojauregui** [inuyaksa/jquery.nicescroll#387]
I'm using the latest versión on a site who have body scroll and div scroll.
When a load the page both scrollbars appears in the correct position, but if I scroll the body a refresh the page, the div scroll shows in wrong position.
I try with the .resize() function but nothing happens:
$("body, .data-container").niceScroll({zindex: 9999, autohidemode: false });
$("body, .data-container").getNiceScroll().resize();
I'm using Chrome.
At last, I change the versión of nicescroll.js to 3.5.0, and works great.

First load
![screen-nicescroll01](https://cloud.githubusercontent.com/assets/1844455/2779808/16b9fb2e-cb00-11e3-8334-83d842d7bc7d.jpg)

Page refresh at bottom
![screen-nicescroll02](https://cloud.githubusercontent.com/assets/1844455/2779809/16bc2be2-cb00-11e3-92bf-d662ab4ec5a8.jpg)

Thanks for the great job and the great plugin!

**Comment by babadofar** [comment]
I have a related problem, where scrollbars appear at the wrong place on resize. 
The issue is when putting scrollbars on a div, and scrolling the window down so that the top of the scrollable element lies above the visible area (negative position top). When I add new content to the scrollable div, and call resize, the wrong top posisiton is returned, so the scrollbar is now positioned above the element. 
Uncommenting the addition of viewport.scrollTop() fixes this problem
https://github.com/inuyaksa/jquery.nicescroll/blob/master/jquery.nicescroll.js#L634

**Comment by IvoPereira** [comment]
@babadofar that fixed it for me either.

3.6.0 does not handles this problem currently.

**Comment by Avinash929** [comment]
It's resolve in newer version.

**Comment by chrisharrisonkiwi** [comment]
Still having trouble version: 3.6.8 with positioning when DOM updates, the horizontal position seems to take a few seconds before correcting itself.
