### ISSUE TITLE
Scrolling nicerscroll container and website at the same time on touch

### ISSUE THREAD

**Issue by Christoph-Wagner** [inuyaksa/jquery.nicescroll#456]
Tested with 3.5.4 and 3.6.0, no changes.  
Happens on WIndows 8.1/IE11 with touch monitor as well as chrome and google browser on android.

When scrolling via touch, the nicescroll container scrolls faster than the normal website, but both scroll at the same time.

Example: http://www.digitalkamera.de/Meldung/Nikon_Coolpix_L27_L820_S31_S5200_S9400_S9500_AW110_P520/8144.aspx (right sidebar)

**Comment by Dennis86** [comment]
I've got the same problem, only difference is that i'm using 2 nested nicescroll's. The inner one scrolls both rails. It works on WIndows 8 with touch, but not on Android stock browser or Android Chrome. 

Did you find a solution for this? Maybe using jquery's :not selector when initiating the plugin or by attaching the scrollbar to parent div instead of body? Just an idea

**Comment by venkateshnadar8** [comment]
@systemruhr 

I would like to add one more strange thing. Android chrome works fine when you apply setting "Request desktop site" but not otherwise.
