### ISSUE TITLE
suited in a popup

### ISSUE THREAD

**Issue by jectychen** [inuyaksa/jquery.nicescroll#525]
when there is a popup,especially use a popup plugin,the scrollbar seems to have a problem to locate;
forgive my poor English!

**Comment by stefanKuijers** [comment]
Please provide a reproduction of the error in a minimal setup in a plunker or jsbin so the owner of the repository can play around with the issue. If you are not specific about your problem it is very hard and time consuming to find out what the problem is and what causes it. 

PS: For me this plugin is working fine in an bootstrap popover.

**Comment by jectychen** [comment]
Thanks for your reply.The attachment is the screenshot of reproduction of the problem.
 
 
------------------ Original ------------------
