### ISSUE TITLE
How to Scroll in Mobile Device

### ISSUE THREAD

**Issue by agungwiseso** [inuyaksa/jquery.nicescroll#626]
Hi, Good morning.

I wanna ask something. How to scroll in mobile device in Div Section ?
I tried `$(".scroll-wrapper").niceScroll({ cursorcolor: "#48c052", touchbehavior: true });` but it does not work.

I also open [http://areaaperta.com/nicescroll/demo.html ](http://areaaperta.com/nicescroll/demo.html)
and I can not scroll the demo in my android.

Thanks

**Comment by xhoskin** [comment]
+

**Comment by pnkjjawale** [comment]
I am facing same problem, on my [http://technodemo.in/wedding](websiteurl). Is there any solution for this issue?

**Comment by venkateshnadar8** [comment]
It seems the latest build got some issue with mobile devices. Please try with 3.6.6 version. I came across the same issue and got fixed with this version. 

I have recently worked on one of my project. You can check the link below:
https://www.youfirst.co.in/who-we-are/overview

Let me know if this solves your problem.

**Comment by inuyaksa** [comment]
#646

**Comment by inuyaksa** [comment]
recent addEventListener changes (and other minor different behavior) broke  touch support.
fixing soon

**Comment by chavals** [comment]
Version 3.7.6 didn't work well with mobile, you need to downgrade to a 3.7.4 version.

**Comment by MatTeague** [comment]
3.7.6 also does work well on mobile for me
