### ISSUE TITLE
NiceScroll Not Working On Android Google Chrome

### ISSUE THREAD

**Issue by MrTIMarshall2512** [inuyaksa/jquery.nicescroll#664]
When accessing my page on an Android operating phone using Google Chrome, the NiceScroll plugin seems to not work for several tested phones some of which will work, however others will not. Various Android versions, all on the latest version of Google Chrome.

**Comment by inuyaksa** [comment]
Please take a screenshot from your phone:
https://nicescroll.areaaperta.com/dojo2/browser.html

**Comment by buddh4** [comment]
I've noticdd a similiar issue, don't know if the problem is related to yours.

On chrome for android when scrolling for example in a panel, the body keeps scrolling and the panel scrolling kind of stucks, even if I set ` nativeparentscrolling: false`.

The only way I could prevent this is by preventing the touchmove default behaviour:

```
$panel.on('touchmove', function(evt) {
    evt.preventDefault();
 });
```

**Comment by buddh4** [comment]
Ok sorry, seems that bower loaded the a wrong version, seems fine with 3.7.0

**Comment by inuyaksa** [comment]
Great!
Now bower works well too?

**Comment by buddh4** [comment]
I use composer and it loads `jquery.nicescroll 3.6.8` even if the install log says:
` Installing bower-asset/jquery.nicescroll (3.7.0)`.

**Comment by MrTIMarshall2512** [comment]
Sorry, I was meant to update this. It seems like maybe some of my website was cached as they saw the scroll bar but couldn't scroll however in recent days it works perfectly fine. Not sure why though!

**Comment by nmaokafor** [comment]
Here is the fix for this issue that worked for me.

When you call the niceScroll function ` $("body").niceScroll();`  in your javascript class, it appears to add an inline style of: `overflow-y: visible` on your body element (because it is inline, it overrides any previous `overflow: hidden` that you may have written in your css file.
 
Simply add overflow: `hidden ! important` in the css of your body element.

Also, make sure that your html element has style of 
```
overflow: hidden;
touch-action: none;

```
